Global:
  debug: false
  use_gpu: true
  epoch_num: 50
  log_smooth_window: 20
  print_batch_step: 5
  save_model_dir: ./output/rec_thai_svtr_rtx5090
  save_epoch_step: 2
  eval_batch_step: [0, 500]
  cal_metric_during_train: true
  pretrained_model: ./pretrain_models/ch_PP-OCRv4_rec_train/best_accuracy
  checkpoints: null
  save_inference_dir: ./inference/thai_rec_rtx5090
  use_visualdl: true
  infer_img: null
  character_dict_path: ./paddle_dataset_30k/thai_dict.txt
  character_type: thai
  max_text_length: 25
  infer_mode: false
  use_space_char: true
  distributed: false
  save_res_path: ./output/rec_thai_svtr_rtx5090/predicts.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 10
  regularizer:
    name: L2
    factor: 0.00002

Architecture:
  model_type: rec
  algorithm: SVTR_LCNet
  Transform: null
  Backbone:
    name: SVTRNet
    img_size: [32, 128]
    out_char_num: 40
    out_channels: 256
    patch_merging: Conv
    embed_dim: [96, 192, 384]
    depth: [3, 6, 3]
    num_heads: [3, 6, 12]
    mixer: [Local,Local,Local,Local,Local,Local,Global,Global,Global,Global,Global,Global]
    local_mixer: [[7, 11], [7, 11], [7, 11]]
    last_stage: true
    prenorm: false
  Neck:
    name: SequenceEncoder
    encoder_type: svtr
    hidden_size: 160
  Head:
    name: CTCHead
    fc_decay: 0.00002

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: paddle_dataset_30k
    label_file_list:
    - paddle_dataset_30k/recognition/train_list.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - CTCLabelEncode:
        max_text_length: 25
    - SVTRRecResizeImg:
        image_shape: [3, 32, 128]
        padding: false
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: true
    batch_size_per_card: 256
    drop_last: true
    num_workers: 8
    use_shared_memory: true

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: paddle_dataset_30k
    label_file_list:
    - paddle_dataset_30k/recognition/val_list.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - CTCLabelEncode:
        max_text_length: 25
    - SVTRRecResizeImg:
        image_shape: [3, 32, 128]
        padding: false
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 128
    num_workers: 8
    use_shared_memory: true
