version: '3.8'

services:
  thai-ocr-training-ngc:
    image: nvcr.io/nvidia/paddlepaddle:24.12-py3
    container_name: thai-ocr-training-ngc
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONPATH=/workspace
      - FLAGS_fraction_of_gpu_memory_to_use=0.8
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - .:/workspace
      - ./models:/workspace/models
      - ./paddle_dataset:/workspace/paddle_dataset
      - ./configs:/workspace/configs
    working_dir: /workspace
    ports:
      - "8888:8888"  # Jupyter
      - "8080:8080"  # API
      - "8501:8501"  # Streamlit
    stdin_open: true
    tty: true
    shm_size: '8gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
